return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.11.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 12,
  height = 102,
  tilewidth = 64,
  tileheight = 64,
  nextlayerid = 10,
  nextobjectid = 75,
  properties = {},
  tilesets = {
    {
      name = "saa_tt_sheet",
      firstgid = 1,
      filename = "../externs/tiled/maps/saa_tt_sheet.tsx"
    }
  },
  layers = {
    {
      type = "group",
      id = 2,
      name = "Group Layer 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      layers = {
        {
          type = "tilelayer",
          x = 0,
          y = 0,
          width = 12,
          height = 102,
          id = 3,
          name = "floor",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          encoding = "lua",
          data = {
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0
          }
        },
        {
          type = "tilelayer",
          x = 0,
          y = 0,
          width = 12,
          height = 102,
          id = 1,
          name = "wall",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          encoding = "lua",
          data = {
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8
          }
        }
      }
    },
    {
      type = "group",
      id = 4,
      name = "Group Layer 2",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      layers = {
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 9,
          name = "Object Layer 5",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 42,
              name = "",
              type = "counter",
              shape = "rectangle",
              x = 64,
              y = 320,
              width = 640,
              height = 192,
              rotation = 0,
              visible = true,
              properties = {}
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 8,
          name = "Object Layer 4",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 13,
              name = "",
              type = "enemy",
              shape = "point",
              x = 384,
              y = 4352,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 14,
              name = "",
              type = "enemy",
              shape = "point",
              x = 496,
              y = 1720,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 55,
              name = "",
              type = "enemy",
              shape = "point",
              x = 348,
              y = 1788,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 15,
              name = "",
              type = "enemy",
              shape = "point",
              x = 245.333,
              y = 1624,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 61,
              name = "",
              type = "enemy",
              shape = "point",
              x = 317.333,
              y = 1777.33,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 16,
              name = "",
              type = "enemy",
              shape = "point",
              x = 369.333,
              y = 1629.33,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 60,
              name = "",
              type = "enemy",
              shape = "point",
              x = 360,
              y = 1858.67,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 17,
              name = "",
              type = "enemy",
              shape = "point",
              x = 390.667,
              y = 1773.33,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 50,
              name = "",
              type = "enemy",
              shape = "point",
              x = 441.333,
              y = 1909.33,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 18,
              name = "",
              type = "enemy",
              shape = "point",
              x = 281.333,
              y = 1722.67,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 51,
              name = "",
              type = "enemy",
              shape = "point",
              x = 400,
              y = 1898.67,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 19,
              name = "",
              type = "enemy",
              shape = "point",
              x = 518.667,
              y = 1908,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 43,
              name = "",
              type = "enemy",
              shape = "point",
              x = 310.667,
              y = 1889.33,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 20,
              name = "",
              type = "enemy",
              shape = "point",
              x = 324,
              y = 1704,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 44,
              name = "",
              type = "enemy",
              shape = "point",
              x = 314.667,
              y = 1854.67,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 21,
              name = "",
              type = "enemy",
              shape = "point",
              x = 490.667,
              y = 1888,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 45,
              name = "",
              type = "enemy",
              shape = "point",
              x = 354.667,
              y = 1926.67,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 22,
              name = "",
              type = "enemy",
              shape = "point",
              x = 405.333,
              y = 1698.67,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 52,
              name = "",
              type = "enemy",
              shape = "point",
              x = 441.333,
              y = 1813.33,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 23,
              name = "",
              type = "enemy",
              shape = "point",
              x = 218.667,
              y = 1689.33,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 54,
              name = "",
              type = "enemy",
              shape = "point",
              x = 281.333,
              y = 1801.33,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 24,
              name = "",
              type = "enemy",
              shape = "point",
              x = 340,
              y = 1644,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 57,
              name = "",
              type = "enemy",
              shape = "point",
              x = 482.667,
              y = 1788,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 25,
              name = "",
              type = "enemy",
              shape = "point",
              x = 397.333,
              y = 1580,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 49,
              name = "",
              type = "enemy",
              shape = "point",
              x = 505.333,
              y = 1828,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 26,
              name = "",
              type = "enemy",
              shape = "point",
              x = 430.667,
              y = 1749.33,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 48,
              name = "",
              type = "enemy",
              shape = "point",
              x = 256,
              y = 1832,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 27,
              name = "",
              type = "enemy",
              shape = "point",
              x = 400,
              y = 3096,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 63,
              name = "",
              type = "enemy",
              shape = "point",
              x = 460,
              y = 3132,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 64,
              name = "",
              type = "enemy",
              shape = "point",
              x = 516,
              y = 3136,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 65,
              name = "",
              type = "enemy",
              shape = "point",
              x = 546,
              y = 3122,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 66,
              name = "",
              type = "enemy",
              shape = "point",
              x = 574,
              y = 3150,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 67,
              name = "",
              type = "enemy",
              shape = "point",
              x = 616,
              y = 3118,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 68,
              name = "",
              type = "enemy",
              shape = "point",
              x = 642,
              y = 3154,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 69,
              name = "",
              type = "enemy",
              shape = "point",
              x = 610,
              y = 3170,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 70,
              name = "",
              type = "enemy",
              shape = "point",
              x = 488,
              y = 3164,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 71,
              name = "",
              type = "enemy",
              shape = "point",
              x = 342,
              y = 3168,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 72,
              name = "",
              type = "enemy",
              shape = "point",
              x = 244,
              y = 3100,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 73,
              name = "",
              type = "enemy",
              shape = "point",
              x = 232,
              y = 3158,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 28,
              name = "",
              type = "enemy",
              shape = "point",
              x = 481.333,
              y = 1641.33,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 59,
              name = "",
              type = "enemy",
              shape = "point",
              x = 525.333,
              y = 1766.67,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 29,
              name = "",
              type = "enemy",
              shape = "point",
              x = 418.667,
              y = 1626.67,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 53,
              name = "",
              type = "enemy",
              shape = "point",
              x = 549.333,
              y = 1757.33,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 30,
              name = "",
              type = "enemy",
              shape = "point",
              x = 406.667,
              y = 3157.33,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 31,
              name = "",
              type = "enemy",
              shape = "point",
              x = 354,
              y = 3132,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 32,
              name = "",
              type = "enemy",
              shape = "point",
              x = 269.333,
              y = 3145.33,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 33,
              name = "",
              type = "enemy",
              shape = "point",
              x = 206.667,
              y = 3128.67,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 34,
              name = "",
              type = "enemy",
              shape = "point",
              x = 309.333,
              y = 3140,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 35,
              name = "",
              type = "enemy",
              shape = "point",
              x = 305.333,
              y = 1601.33,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 46,
              name = "",
              type = "enemy",
              shape = "point",
              x = 466.667,
              y = 1849.33,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 36,
              name = "",
              type = "enemy",
              shape = "point",
              x = 466.667,
              y = 1694.67,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 58,
              name = "",
              type = "enemy",
              shape = "point",
              x = 457.333,
              y = 1784,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 37,
              name = "",
              type = "enemy",
              shape = "point",
              x = 358.667,
              y = 1716,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 56,
              name = "",
              type = "enemy",
              shape = "point",
              x = 409.333,
              y = 1833.33,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 38,
              name = "",
              type = "enemy",
              shape = "point",
              x = 288,
              y = 1656,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 47,
              name = "",
              type = "enemy",
              shape = "point",
              x = 542.667,
              y = 1854.67,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 39,
              name = "",
              type = "enemy",
              shape = "point",
              x = 420,
              y = 3178.67,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 40,
              name = "",
              type = "enemy",
              shape = "point",
              x = 213.333,
              y = 1752,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 62,
              name = "",
              type = "enemy",
              shape = "point",
              x = 258.667,
              y = 1766.67,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 41,
              name = "",
              type = "enemy",
              shape = "point",
              x = 156,
              y = 3128.67,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 7,
          name = "Object Layer 3",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 8,
              name = "x2",
              type = "trigger_cloner",
              shape = "rectangle",
              x = 128,
              y = 4736,
              width = 512,
              height = 32,
              rotation = 0,
              visible = true,
              properties = {
                ["multiply"] = 2
              }
            },
            {
              id = 9,
              name = "x2",
              type = "trigger_cloner",
              shape = "rectangle",
              x = 128,
              y = 4032,
              width = 512,
              height = 32,
              rotation = 0,
              visible = true,
              properties = {
                ["multiply"] = 2
              }
            },
            {
              id = 10,
              name = "x3",
              type = "trigger_cloner",
              shape = "rectangle",
              x = 128,
              y = 3584,
              width = 512,
              height = 32,
              rotation = 0,
              visible = true,
              properties = {
                ["multiply"] = 3
              }
            },
            {
              id = 11,
              name = "x4",
              type = "trigger_cloner",
              shape = "rectangle",
              x = 128,
              y = 2624,
              width = 512,
              height = 18,
              rotation = 0,
              visible = true,
              properties = {
                ["multiply"] = 4
              }
            },
            {
              id = 74,
              name = "x4",
              type = "trigger_cloner",
              shape = "rectangle",
              x = 128,
              y = 2496,
              width = 512,
              height = 18,
              rotation = 0,
              visible = true,
              properties = {
                ["multiply"] = 4
              }
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 6,
          name = "Object Layer 2",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 4,
              name = "",
              type = "ball",
              shape = "point",
              x = 381.333,
              y = 5788,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 5,
          name = "Object Layer 1",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 1,
              name = "start",
              type = "point_start",
              shape = "point",
              x = 384,
              y = 5824,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            }
          }
        }
      }
    }
  }
}
