return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.11.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 12,
  height = 86,
  tilewidth = 64,
  tileheight = 64,
  nextlayerid = 10,
  nextobjectid = 65,
  properties = {},
  tilesets = {
    {
      name = "saa_tt_sheet",
      firstgid = 1,
      filename = "../externs/tiled/maps/saa_tt_sheet.tsx"
    }
  },
  layers = {
    {
      type = "group",
      id = 2,
      name = "Group Layer 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      layers = {
        {
          type = "tilelayer",
          x = 0,
          y = 0,
          width = 12,
          height = 86,
          id = 3,
          name = "floor",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          encoding = "lua",
          data = {
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
            0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
            0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
            0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
            0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
            0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
            0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0
          }
        },
        {
          type = "tilelayer",
          x = 0,
          y = 0,
          width = 12,
          height = 86,
          id = 1,
          name = "wall",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          encoding = "lua",
          data = {
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 9, 0, 0, 0, 0, 0, 0, 0, 0, 10, 8,
            0, 8, 9, 0, 0, 0, 0, 0, 0, 10, 8, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 9, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 0, 8, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 0, 8, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 0, 8, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 0, 8, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 0, 8, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 0, 8, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 8, 8, 2, 0, 0, 0, 0, 0, 8, 8, 0,
            0, 8, 2, 0, 0, 0, 0, 0, 0, 3, 8, 0,
            0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0,
            0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0,
            0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0,
            0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0,
            0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0,
            0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0,
            0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0,
            0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0,
            0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0,
            0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0,
            0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0,
            0, 8, 9, 0, 0, 0, 0, 0, 0, 10, 8, 0,
            0, 0, 8, 9, 0, 0, 0, 0, 10, 8, 0, 0,
            0, 0, 0, 8, 0, 0, 0, 0, 8, 0, 0, 0,
            0, 0, 0, 8, 0, 0, 0, 0, 8, 0, 0, 0,
            0, 0, 0, 8, 0, 0, 0, 0, 8, 0, 0, 0,
            0, 0, 0, 8, 0, 0, 0, 0, 8, 0, 0, 0,
            0, 0, 0, 8, 0, 0, 0, 0, 8, 0, 0, 0,
            0, 0, 0, 8, 0, 0, 0, 0, 8, 0, 0, 0,
            0, 0, 0, 8, 0, 0, 0, 0, 8, 0, 0, 0,
            0, 0, 8, 2, 0, 0, 0, 0, 3, 8, 0, 0,
            0, 8, 2, 0, 0, 0, 0, 0, 0, 3, 8, 0,
            0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0,
            0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0,
            0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0,
            0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0,
            0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0,
            0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0,
            0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0
          }
        }
      }
    },
    {
      type = "group",
      id = 4,
      name = "Group Layer 2",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      layers = {
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 5,
          name = "Object Layer 1",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 1,
              name = "start",
              type = "point_start",
              shape = "point",
              x = 384,
              y = 4928,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 6,
          name = "Object Layer 2",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 2,
              name = "",
              type = "ball",
              shape = "point",
              x = 302,
              y = 5096,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 3,
              name = "",
              type = "ball",
              shape = "point",
              x = 360,
              y = 5108,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 4,
              name = "",
              type = "ball",
              shape = "point",
              x = 418,
              y = 5110,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 5,
              name = "",
              type = "ball",
              shape = "point",
              x = 470,
              y = 5100,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 7,
          name = "Object Layer 3",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 6,
              name = "x2",
              type = "trigger_cloner",
              shape = "rectangle",
              x = 512,
              y = 4224,
              width = 128,
              height = 32,
              rotation = 0,
              visible = true,
              properties = {
                ["multiply"] = 2
              }
            },
            {
              id = 7,
              name = "x2",
              type = "trigger_cloner",
              shape = "rectangle",
              x = 192,
              y = 3712,
              width = 128,
              height = 32,
              rotation = 0,
              visible = true,
              properties = {
                ["multiply"] = 2
              }
            },
            {
              id = 8,
              name = "x2",
              type = "trigger_cloner",
              shape = "rectangle",
              x = 320,
              y = 2880,
              width = 128,
              height = 32,
              rotation = 0,
              visible = true,
              properties = {
                ["multiply"] = 2
              }
            },
            {
              id = 9,
              name = "x4",
              type = "trigger_cloner",
              shape = "rectangle",
              x = 192,
              y = 1856,
              width = 128,
              height = 32,
              rotation = 0,
              visible = true,
              properties = {
                ["multiply"] = 4
              }
            },
            {
              id = 10,
              name = "x2",
              type = "trigger_cloner",
              shape = "rectangle",
              x = 448,
              y = 1856,
              width = 128,
              height = 32,
              rotation = 0,
              visible = true,
              properties = {
                ["multiply"] = 2
              }
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 8,
          name = "Object Layer 4",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 11,
              name = "",
              type = "enemy",
              shape = "point",
              x = 430,
              y = 4020,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 14,
              name = "",
              type = "enemy",
              shape = "point",
              x = 430,
              y = 3058,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 17,
              name = "",
              type = "enemy",
              shape = "point",
              x = 548,
              y = 2450,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 18,
              name = "",
              type = "enemy",
              shape = "point",
              x = 215.333,
              y = 2435.33,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 19,
              name = "",
              type = "enemy",
              shape = "point",
              x = 546.667,
              y = 2396,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 20,
              name = "",
              type = "enemy",
              shape = "point",
              x = 246.667,
              y = 2400.67,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 21,
              name = "",
              type = "enemy",
              shape = "point",
              x = 546,
              y = 2645.33,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 22,
              name = "",
              type = "enemy",
              shape = "point",
              x = 223.333,
              y = 2626.67,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 23,
              name = "",
              type = "enemy",
              shape = "point",
              x = 530,
              y = 2607.33,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 24,
              name = "",
              type = "enemy",
              shape = "point",
              x = 248.667,
              y = 2582.67,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 25,
              name = "",
              type = "enemy",
              shape = "point",
              x = 539.333,
              y = 2554.67,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 26,
              name = "",
              type = "enemy",
              shape = "point",
              x = 223.333,
              y = 2542.67,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 27,
              name = "",
              type = "enemy",
              shape = "point",
              x = 555.333,
              y = 2514.67,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 28,
              name = "",
              type = "enemy",
              shape = "point",
              x = 252.667,
              y = 2484,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 29,
              name = "",
              type = "enemy",
              shape = "point",
              x = 512.667,
              y = 2434.67,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 30,
              name = "",
              type = "enemy",
              shape = "point",
              x = 212.667,
              y = 2488,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 31,
              name = "",
              type = "enemy",
              shape = "point",
              x = 526,
              y = 2485.33,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 15,
              name = "",
              type = "enemy",
              shape = "point",
              x = 382,
              y = 3054,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 16,
              name = "",
              type = "enemy",
              shape = "point",
              x = 338,
              y = 3054,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 12,
              name = "",
              type = "enemy",
              shape = "point",
              x = 384,
              y = 4036,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 13,
              name = "",
              type = "enemy",
              shape = "point",
              x = 340,
              y = 4018,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 33,
              name = "",
              type = "enemy",
              shape = "point",
              x = 301.545,
              y = 1217.09,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 64,
              name = "",
              type = "enemy",
              shape = "point",
              x = 465.545,
              y = 1234.09,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 34,
              name = "",
              type = "enemy",
              shape = "point",
              x = 239.394,
              y = 1275.76,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 62,
              name = "",
              type = "enemy",
              shape = "point",
              x = 405.394,
              y = 1282.76,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 35,
              name = "",
              type = "enemy",
              shape = "point",
              x = 260.394,
              y = 1249.76,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 63,
              name = "",
              type = "enemy",
              shape = "point",
              x = 440.394,
              y = 1258.76,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 36,
              name = "",
              type = "enemy",
              shape = "point",
              x = 346.394,
              y = 1240.76,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 37,
              name = "",
              type = "enemy",
              shape = "point",
              x = 415.394,
              y = 1207.76,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 38,
              name = "",
              type = "enemy",
              shape = "point",
              x = 509.394,
              y = 1344.76,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 39,
              name = "",
              type = "enemy",
              shape = "point",
              x = 528.394,
              y = 1252.76,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 40,
              name = "",
              type = "enemy",
              shape = "point",
              x = 525.394,
              y = 1301.76,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 41,
              name = "",
              type = "enemy",
              shape = "point",
              x = 431.394,
              y = 1356.76,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 53,
              name = "",
              type = "enemy",
              shape = "point",
              x = 436.394,
              y = 1308.76,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 42,
              name = "",
              type = "enemy",
              shape = "point",
              x = 310.394,
              y = 1319.76,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 60,
              name = "",
              type = "enemy",
              shape = "point",
              x = 476.394,
              y = 1326.76,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 54,
              name = "",
              type = "enemy",
              shape = "point",
              x = 279.394,
              y = 1371.76,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 59,
              name = "",
              type = "enemy",
              shape = "point",
              x = 469.394,
              y = 1376.76,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 43,
              name = "",
              type = "enemy",
              shape = "point",
              x = 373.394,
              y = 1386.76,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 52,
              name = "",
              type = "enemy",
              shape = "point",
              x = 283.394,
              y = 1286.76,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 61,
              name = "",
              type = "enemy",
              shape = "point",
              x = 467.394,
              y = 1285.76,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 44,
              name = "",
              type = "enemy",
              shape = "point",
              x = 390.394,
              y = 1321.76,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 55,
              name = "",
              type = "enemy",
              shape = "point",
              x = 356.394,
              y = 1349.76,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 45,
              name = "",
              type = "enemy",
              shape = "point",
              x = 340.394,
              y = 1298.76,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 46,
              name = "",
              type = "enemy",
              shape = "point",
              x = 406.394,
              y = 1400.76,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 47,
              name = "",
              type = "enemy",
              shape = "point",
              x = 483.394,
              y = 1402.76,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 48,
              name = "",
              type = "enemy",
              shape = "point",
              x = 297.394,
              y = 1387.76,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 58,
              name = "",
              type = "enemy",
              shape = "point",
              x = 521.394,
              y = 1385.76,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 51,
              name = "",
              type = "enemy",
              shape = "point",
              x = 263.394,
              y = 1415.76,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 57,
              name = "",
              type = "enemy",
              shape = "point",
              x = 429.394,
              y = 1422.76,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 49,
              name = "",
              type = "enemy",
              shape = "point",
              x = 349.394,
              y = 1416.76,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 50,
              name = "",
              type = "enemy",
              shape = "point",
              x = 315.394,
              y = 1444.76,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 56,
              name = "",
              type = "enemy",
              shape = "point",
              x = 481.394,
              y = 1451.76,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 9,
          name = "Object Layer 5",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 32,
              name = "",
              type = "counter",
              shape = "rectangle",
              x = 128,
              y = 384,
              width = 512,
              height = 256,
              rotation = 0,
              visible = true,
              properties = {}
            }
          }
        }
      }
    }
  }
}
