return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.11.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 12,
  height = 52,
  tilewidth = 64,
  tileheight = 64,
  nextlayerid = 10,
  nextobjectid = 88,
  properties = {},
  tilesets = {
    {
      name = "saa_tt_sheet",
      firstgid = 1,
      filename = "../externs/tiled/maps/saa_tt_sheet.tsx"
    }
  },
  layers = {
    {
      type = "group",
      id = 2,
      name = "Group Layer 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      layers = {
        {
          type = "tilelayer",
          x = 0,
          y = 0,
          width = 12,
          height = 52,
          id = 1,
          name = "floor",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          encoding = "lua",
          data = {
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0
          }
        },
        {
          type = "tilelayer",
          x = 0,
          y = 0,
          width = 12,
          height = 52,
          id = 3,
          name = "wall",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          encoding = "lua",
          data = {
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0
          }
        }
      }
    },
    {
      type = "group",
      id = 4,
      name = "Group Layer 2",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      layers = {
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 5,
          name = "Object Layer 1",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 1,
              name = "Start",
              type = "point_start",
              shape = "point",
              x = 384,
              y = 3008,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 6,
          name = "Object Layer 2",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 2,
              name = "",
              type = "ball",
              shape = "point",
              x = 529.366,
              y = 2993.25,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 7,
          name = "Object Layer 3",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 3,
              name = "x8",
              type = "trigger_cloner",
              shape = "rectangle",
              x = 276,
              y = 2636,
              width = 140,
              height = 36,
              rotation = 0,
              visible = true,
              properties = {
                ["multiply"] = 8
              }
            },
            {
              id = 4,
              name = "x6",
              type = "trigger_cloner",
              shape = "rectangle",
              x = 405.333,
              y = 2188,
              width = 140,
              height = 36,
              rotation = 0,
              visible = true,
              properties = {
                ["multiply"] = 6
              }
            },
            {
              id = 6,
              name = "x4",
              type = "trigger_cloner",
              shape = "rectangle",
              x = 214.667,
              y = 1738.67,
              width = 140,
              height = 36,
              rotation = 0,
              visible = true,
              properties = {
                ["multiply"] = 4
              }
            },
            {
              id = 7,
              name = "x4",
              type = "trigger_cloner",
              shape = "rectangle",
              x = 406.667,
              y = 1290.67,
              width = 140,
              height = 36,
              rotation = 0,
              visible = true,
              properties = {
                ["multiply"] = 4
              }
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 8,
          name = "Object Layer 4",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 8,
              name = "",
              type = "enemy",
              shape = "point",
              x = 297.333,
              y = 2424,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 21,
              name = "",
              type = "enemy",
              shape = "point",
              x = 365.333,
              y = 1952,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 16,
              name = "",
              type = "enemy",
              shape = "point",
              x = 292,
              y = 2356,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 27,
              name = "",
              type = "enemy",
              shape = "point",
              x = 384,
              y = 1928,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 9,
              name = "",
              type = "enemy",
              shape = "point",
              x = 322.667,
              y = 2413.33,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 24,
              name = "",
              type = "enemy",
              shape = "point",
              x = 345.333,
              y = 1930.67,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 18,
              name = "",
              type = "enemy",
              shape = "point",
              x = 317.333,
              y = 2345.33,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 29,
              name = "",
              type = "enemy",
              shape = "point",
              x = 418.667,
              y = 1986.67,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 30,
              name = "",
              type = "enemy",
              shape = "point",
              x = 373.333,
              y = 1496,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 41,
              name = "",
              type = "enemy",
              shape = "point",
              x = 394.667,
              y = 816,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 73,
              name = "",
              type = "enemy",
              shape = "point",
              x = 382.667,
              y = 932,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 57,
              name = "",
              type = "enemy",
              shape = "point",
              x = 481.333,
              y = 816,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 72,
              name = "",
              type = "enemy",
              shape = "point",
              x = 464,
              y = 908,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 52,
              name = "",
              type = "enemy",
              shape = "point",
              x = 273.333,
              y = 746.667,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 63,
              name = "",
              type = "enemy",
              shape = "point",
              x = 361.333,
              y = 744,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 83,
              name = "",
              type = "enemy",
              shape = "point",
              x = 416,
              y = 861.333,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 31,
              name = "",
              type = "enemy",
              shape = "point",
              x = 409.333,
              y = 1525.33,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 39,
              name = "",
              type = "enemy",
              shape = "point",
              x = 448,
              y = 800,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 75,
              name = "",
              type = "enemy",
              shape = "point",
              x = 533.333,
              y = 922.667,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 53,
              name = "",
              type = "enemy",
              shape = "point",
              x = 330.667,
              y = 712,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 65,
              name = "",
              type = "enemy",
              shape = "point",
              x = 429.333,
              y = 756,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 87,
              name = "",
              type = "enemy",
              shape = "point",
              x = 308,
              y = 844,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 32,
              name = "",
              type = "enemy",
              shape = "point",
              x = 412,
              y = 1473.33,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 43,
              name = "",
              type = "enemy",
              shape = "point",
              x = 366.667,
              y = 674.667,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 68,
              name = "",
              type = "enemy",
              shape = "point",
              x = 462.667,
              y = 700,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 50,
              name = "",
              type = "enemy",
              shape = "point",
              x = 428,
              y = 716,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 62,
              name = "",
              type = "enemy",
              shape = "point",
              x = 473.333,
              y = 757.333,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 86,
              name = "",
              type = "enemy",
              shape = "point",
              x = 526.667,
              y = 853.333,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 33,
              name = "",
              type = "enemy",
              shape = "point",
              x = 341.333,
              y = 1458.67,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 44,
              name = "",
              type = "enemy",
              shape = "point",
              x = 282.667,
              y = 678.667,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 67,
              name = "",
              type = "enemy",
              shape = "point",
              x = 378.667,
              y = 704,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 49,
              name = "",
              type = "enemy",
              shape = "point",
              x = 322.667,
              y = 665.333,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 61,
              name = "",
              type = "enemy",
              shape = "point",
              x = 425.333,
              y = 826.667,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 76,
              name = "",
              type = "enemy",
              shape = "point",
              x = 425.333,
              y = 916,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 34,
              name = "",
              type = "enemy",
              shape = "point",
              x = 338.667,
              y = 1502.67,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 40,
              name = "",
              type = "enemy",
              shape = "point",
              x = 244,
              y = 782.667,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 79,
              name = "",
              type = "enemy",
              shape = "point",
              x = 234.667,
              y = 830.667,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 58,
              name = "",
              type = "enemy",
              shape = "point",
              x = 340,
              y = 808,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 74,
              name = "",
              type = "enemy",
              shape = "point",
              x = 352,
              y = 841.333,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 46,
              name = "",
              type = "enemy",
              shape = "point",
              x = 370.667,
              y = 865.333,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 69,
              name = "",
              type = "enemy",
              shape = "point",
              x = 254.667,
              y = 882.667,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 55,
              name = "",
              type = "enemy",
              shape = "point",
              x = 461.333,
              y = 841.333,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 70,
              name = "",
              type = "enemy",
              shape = "point",
              x = 485.333,
              y = 946.667,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 51,
              name = "",
              type = "enemy",
              shape = "point",
              x = 236,
              y = 736,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 64,
              name = "",
              type = "enemy",
              shape = "point",
              x = 332,
              y = 761.333,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 84,
              name = "",
              type = "enemy",
              shape = "point",
              x = 320,
              y = 889.333,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 35,
              name = "",
              type = "enemy",
              shape = "point",
              x = 369.333,
              y = 1537.33,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 38,
              name = "",
              type = "enemy",
              shape = "point",
              x = 274.667,
              y = 817.333,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 71,
              name = "",
              type = "enemy",
              shape = "point",
              x = 226.667,
              y = 889.333,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 56,
              name = "",
              type = "enemy",
              shape = "point",
              x = 309.333,
              y = 797.333,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 77,
              name = "",
              type = "enemy",
              shape = "point",
              x = 276,
              y = 918.667,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 36,
              name = "",
              type = "enemy",
              shape = "point",
              x = 376,
              y = 1445.33,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 45,
              name = "",
              type = "enemy",
              shape = "point",
              x = 300,
              y = 758.667,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 81,
              name = "",
              type = "enemy",
              shape = "point",
              x = 286.667,
              y = 882.667,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 60,
              name = "",
              type = "enemy",
              shape = "point",
              x = 396,
              y = 784,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 78,
              name = "",
              type = "enemy",
              shape = "point",
              x = 369.333,
              y = 790.667,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 47,
              name = "",
              type = "enemy",
              shape = "point",
              x = 408,
              y = 748,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 82,
              name = "",
              type = "enemy",
              shape = "point",
              x = 404,
              y = 904,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 59,
              name = "",
              type = "enemy",
              shape = "point",
              x = 489.333,
              y = 780,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 80,
              name = "",
              type = "enemy",
              shape = "point",
              x = 505.333,
              y = 900,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 54,
              name = "",
              type = "enemy",
              shape = "point",
              x = 257.333,
              y = 681.333,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 66,
              name = "",
              type = "enemy",
              shape = "point",
              x = 353.333,
              y = 706.667,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 37,
              name = "",
              type = "enemy",
              shape = "point",
              x = 430.667,
              y = 1492,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 42,
              name = "",
              type = "enemy",
              shape = "point",
              x = 497.333,
              y = 678.667,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 48,
              name = "",
              type = "enemy",
              shape = "point",
              x = 504,
              y = 729.333,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 85,
              name = "",
              type = "enemy",
              shape = "point",
              x = 473.333,
              y = 876,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 10,
              name = "",
              type = "enemy",
              shape = "point",
              x = 342.667,
              y = 2434.67,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 20,
              name = "",
              type = "enemy",
              shape = "point",
              x = 348,
              y = 1965.33,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 15,
              name = "",
              type = "enemy",
              shape = "point",
              x = 337.333,
              y = 2366.67,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 26,
              name = "",
              type = "enemy",
              shape = "point",
              x = 412,
              y = 1942.67,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 11,
              name = "",
              type = "enemy",
              shape = "point",
              x = 361.333,
              y = 2416,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 23,
              name = "",
              type = "enemy",
              shape = "point",
              x = 380,
              y = 1956,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 17,
              name = "",
              type = "enemy",
              shape = "point",
              x = 356,
              y = 2348,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 28,
              name = "",
              type = "enemy",
              shape = "point",
              x = 366.667,
              y = 1989.33,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 12,
              name = "",
              type = "enemy",
              shape = "point",
              x = 381.333,
              y = 2444,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 19,
              name = "",
              type = "enemy",
              shape = "point",
              x = 436,
              y = 1976,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 14,
              name = "",
              type = "enemy",
              shape = "point",
              x = 376,
              y = 2376,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 25,
              name = "",
              type = "enemy",
              shape = "point",
              x = 390.667,
              y = 1978.67,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 13,
              name = "",
              type = "enemy",
              shape = "point",
              x = 400,
              y = 2416,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 22,
              name = "",
              type = "enemy",
              shape = "point",
              x = 386.667,
              y = 2001.33,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 9,
          name = "Object Layer 5",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 5,
              name = "",
              type = "counter",
              shape = "rectangle",
              x = 197,
              y = 162,
              width = 373,
              height = 138.667,
              rotation = 0,
              visible = true,
              properties = {}
            }
          }
        }
      }
    }
  }
}
