return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.11.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 12,
  height = 96,
  tilewidth = 64,
  tileheight = 64,
  nextlayerid = 10,
  nextobjectid = 85,
  properties = {},
  tilesets = {
    {
      name = "saa_tt_sheet",
      firstgid = 1,
      filename = "../externs/tiled/maps/saa_tt_sheet.tsx"
    }
  },
  layers = {
    {
      type = "group",
      id = 2,
      name = "Group Layer 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      layers = {
        {
          type = "tilelayer",
          x = 0,
          y = 0,
          width = 12,
          height = 96,
          id = 1,
          name = "floor",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          encoding = "lua",
          data = {
            0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
            0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
            0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
            0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
            0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
            0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
            0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
            0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
            0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
            0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
            0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0
          }
        },
        {
          type = "tilelayer",
          x = 0,
          y = 0,
          width = 12,
          height = 96,
          id = 3,
          name = "wall",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          encoding = "lua",
          data = {
            0, 0, 0, 8, 0, 0, 0, 0, 8, 0, 0, 0,
            0, 0, 0, 8, 0, 0, 0, 0, 8, 0, 0, 0,
            0, 0, 0, 8, 0, 0, 0, 0, 8, 0, 0, 0,
            0, 0, 0, 8, 0, 0, 0, 0, 8, 0, 0, 0,
            0, 0, 0, 8, 0, 0, 0, 0, 8, 0, 0, 0,
            0, 0, 0, 8, 0, 0, 0, 0, 8, 0, 0, 0,
            0, 0, 0, 8, 0, 0, 0, 0, 8, 0, 0, 0,
            0, 0, 0, 8, 0, 0, 0, 0, 8, 0, 0, 0,
            0, 0, 0, 8, 0, 0, 0, 0, 8, 0, 0, 0,
            0, 0, 0, 8, 0, 0, 0, 0, 8, 0, 0, 0,
            0, 0, 8, 4, 0, 0, 0, 0, 5, 8, 0, 0,
            0, 0, 8, 11, 0, 0, 0, 0, 12, 8, 0, 0,
            0, 8, 4, 0, 0, 0, 0, 0, 0, 5, 8, 0,
            0, 8, 11, 0, 0, 0, 0, 0, 0, 12, 8, 0,
            8, 4, 0, 0, 0, 0, 0, 0, 0, 0, 5, 8,
            8, 11, 0, 0, 0, 0, 0, 0, 0, 0, 12, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
            0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0,
            0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0,
            0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0,
            0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0,
            0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0,
            0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0,
            0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0,
            0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0,
            0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0,
            0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0,
            0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0,
            0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0,
            0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0,
            0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0,
            0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0,
            0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0,
            0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0,
            0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0,
            0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0,
            0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0,
            0, 8, 8, 0, 0, 0, 0, 0, 0, 8, 8, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 0, 8, 0, 0, 0, 0, 0, 0, 8, 0, 0,
            0, 8, 8, 0, 0, 0, 0, 0, 0, 8, 8, 0,
            0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0,
            0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0,
            0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0,
            0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0,
            0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0,
            0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0
          }
        }
      }
    },
    {
      type = "group",
      id = 4,
      name = "Group Layer 2",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      layers = {
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 5,
          name = "Object Layer 1",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 1,
              name = "Start",
              type = "point_start",
              shape = "point",
              x = 384,
              y = 5568,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 6,
          name = "Object Layer 2",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 2,
              name = "",
              type = "ball",
              shape = "point",
              x = 329.333,
              y = 5628,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 3,
              name = "",
              type = "ball",
              shape = "point",
              x = 382.667,
              y = 5678.67,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 4,
              name = "",
              type = "ball",
              shape = "point",
              x = 469.333,
              y = 5645.33,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 5,
              name = "",
              type = "ball",
              shape = "point",
              x = 466.667,
              y = 5757.33,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 6,
              name = "",
              type = "ball",
              shape = "point",
              x = 324,
              y = 5725.33,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 7,
              name = "",
              type = "ball",
              shape = "point",
              x = 324,
              y = 5776,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 8,
              name = "",
              type = "ball",
              shape = "point",
              x = 358.667,
              y = 5790.67,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 9,
              name = "",
              type = "ball",
              shape = "point",
              x = 417.333,
              y = 5812,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 10,
              name = "",
              type = "ball",
              shape = "point",
              x = 406.667,
              y = 5881.33,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 11,
              name = "",
              type = "ball",
              shape = "point",
              x = 349.333,
              y = 5817.33,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 12,
              name = "",
              type = "ball",
              shape = "point",
              x = 281.333,
              y = 5836,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 13,
              name = "",
              type = "ball",
              shape = "point",
              x = 276,
              y = 5768,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 14,
              name = "",
              type = "ball",
              shape = "point",
              x = 392,
              y = 5716,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 15,
              name = "",
              type = "ball",
              shape = "point",
              x = 445.333,
              y = 5741.33,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 16,
              name = "",
              type = "ball",
              shape = "point",
              x = 449.333,
              y = 5693.33,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 17,
              name = "",
              type = "ball",
              shape = "point",
              x = 422.667,
              y = 5678.67,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 18,
              name = "",
              type = "ball",
              shape = "point",
              x = 408,
              y = 5638.67,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 19,
              name = "",
              type = "ball",
              shape = "point",
              x = 324,
              y = 5657.33,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 20,
              name = "",
              type = "ball",
              shape = "point",
              x = 314.667,
              y = 5698.67,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 21,
              name = "",
              type = "ball",
              shape = "point",
              x = 277.333,
              y = 5669.33,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 22,
              name = "",
              type = "ball",
              shape = "point",
              x = 369.333,
              y = 5749.33,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 23,
              name = "",
              type = "ball",
              shape = "point",
              x = 440,
              y = 5800,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 24,
              name = "",
              type = "ball",
              shape = "point",
              x = 462.667,
              y = 5846.67,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 25,
              name = "",
              type = "ball",
              shape = "point",
              x = 486.667,
              y = 5796,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 26,
              name = "",
              type = "ball",
              shape = "point",
              x = 490.667,
              y = 5862.67,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 27,
              name = "",
              type = "ball",
              shape = "point",
              x = 437.333,
              y = 5893.33,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 28,
              name = "",
              type = "ball",
              shape = "point",
              x = 354.667,
              y = 5876,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 29,
              name = "",
              type = "ball",
              shape = "point",
              x = 318.667,
              y = 5908,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 30,
              name = "",
              type = "ball",
              shape = "point",
              x = 333.333,
              y = 5836,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 31,
              name = "",
              type = "ball",
              shape = "point",
              x = 306.667,
              y = 5833.33,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 32,
              name = "",
              type = "ball",
              shape = "point",
              x = 489.333,
              y = 5696,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 33,
              name = "",
              type = "ball",
              shape = "point",
              x = 408,
              y = 5725.33,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 7,
          name = "Object Layer 3",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 34,
              name = "x0",
              type = "trigger_cloner",
              shape = "rectangle",
              x = 192,
              y = 4736,
              width = 128,
              height = 64,
              rotation = 0,
              visible = true,
              properties = {
                ["multiply"] = 0
              }
            },
            {
              id = 35,
              name = "x2",
              type = "trigger_cloner",
              shape = "rectangle",
              x = 448,
              y = 4736,
              width = 128,
              height = 64,
              rotation = 0,
              visible = true,
              properties = {
                ["multiply"] = 2
              }
            },
            {
              id = 36,
              name = "x3",
              type = "trigger_cloner",
              shape = "rectangle",
              x = 296,
              y = 4356,
              width = 170,
              height = 28,
              rotation = 0,
              visible = true,
              properties = {
                ["multiply"] = 3
              }
            },
            {
              id = 37,
              name = "x0",
              type = "trigger_cloner",
              shape = "rectangle",
              x = 64,
              y = 1088,
              width = 128,
              height = 2112,
              rotation = 0,
              visible = true,
              properties = {
                ["multiply"] = 0
              }
            },
            {
              id = 38,
              name = "x0",
              type = "trigger_cloner",
              shape = "rectangle",
              x = 576,
              y = 1088,
              width = 128,
              height = 2112,
              rotation = 0,
              visible = true,
              properties = {
                ["multiply"] = 0
              }
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 8,
          name = "Object Layer 4",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 39,
              name = "",
              type = "enemy",
              shape = "point",
              x = 250,
              y = 5086,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 40,
              name = "",
              type = "enemy",
              shape = "point",
              x = 348,
              y = 5086,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 41,
              name = "",
              type = "enemy",
              shape = "point",
              x = 486,
              y = 5078,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 42,
              name = "",
              type = "enemy",
              shape = "point",
              x = 272,
              y = 3750,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 43,
              name = "",
              type = "enemy",
              shape = "point",
              x = 302,
              y = 3736,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 44,
              name = "",
              type = "enemy",
              shape = "point",
              x = 324,
              y = 3750,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 45,
              name = "",
              type = "enemy",
              shape = "point",
              x = 346,
              y = 3762,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 46,
              name = "",
              type = "enemy",
              shape = "point",
              x = 364,
              y = 3736,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 47,
              name = "",
              type = "enemy",
              shape = "point",
              x = 390,
              y = 3744,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 48,
              name = "",
              type = "enemy",
              shape = "point",
              x = 396,
              y = 3766,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 49,
              name = "",
              type = "enemy",
              shape = "point",
              x = 426,
              y = 3744,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 50,
              name = "",
              type = "enemy",
              shape = "point",
              x = 466,
              y = 3748,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 51,
              name = "",
              type = "enemy",
              shape = "point",
              x = 480,
              y = 3766,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 52,
              name = "",
              type = "enemy",
              shape = "point",
              x = 508,
              y = 3750,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 53,
              name = "",
              type = "enemy",
              shape = "point",
              x = 516,
              y = 3770,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 54,
              name = "",
              type = "enemy",
              shape = "point",
              x = 496,
              y = 3788,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 55,
              name = "",
              type = "enemy",
              shape = "point",
              x = 448,
              y = 3774,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 56,
              name = "",
              type = "enemy",
              shape = "point",
              x = 420,
              y = 3784,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 57,
              name = "",
              type = "enemy",
              shape = "point",
              x = 384,
              y = 3790,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 58,
              name = "",
              type = "enemy",
              shape = "point",
              x = 350,
              y = 3780,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 59,
              name = "",
              type = "enemy",
              shape = "point",
              x = 330,
              y = 3782,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 60,
              name = "",
              type = "enemy",
              shape = "point",
              x = 302,
              y = 3786,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 61,
              name = "",
              type = "enemy",
              shape = "point",
              x = 280,
              y = 3764,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 62,
              name = "",
              type = "enemy",
              shape = "point",
              x = 258,
              y = 3772,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 63,
              name = "",
              type = "enemy",
              shape = "point",
              x = 224,
              y = 3800,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 64,
              name = "",
              type = "enemy",
              shape = "point",
              x = 300,
              y = 2732,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 65,
              name = "",
              type = "enemy",
              shape = "point",
              x = 326,
              y = 2730,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 66,
              name = "",
              type = "enemy",
              shape = "point",
              x = 352,
              y = 2736,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 67,
              name = "",
              type = "enemy",
              shape = "point",
              x = 342,
              y = 2772,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 68,
              name = "",
              type = "enemy",
              shape = "point",
              x = 320,
              y = 2764,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 69,
              name = "",
              type = "enemy",
              shape = "point",
              x = 470,
              y = 2392,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 70,
              name = "",
              type = "enemy",
              shape = "point",
              x = 480,
              y = 2044,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 71,
              name = "",
              type = "enemy",
              shape = "point",
              x = 462,
              y = 2050,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 72,
              name = "",
              type = "enemy",
              shape = "point",
              x = 468,
              y = 2056,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 73,
              name = "",
              type = "enemy",
              shape = "point",
              x = 486,
              y = 2070,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 74,
              name = "",
              type = "enemy",
              shape = "point",
              x = 504,
              y = 2072,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 75,
              name = "",
              type = "enemy",
              shape = "point",
              x = 476,
              y = 2102,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 76,
              name = "",
              type = "enemy",
              shape = "point",
              x = 442,
              y = 2082,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 77,
              name = "",
              type = "enemy",
              shape = "point",
              x = 252,
              y = 1334,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 78,
              name = "",
              type = "enemy",
              shape = "point",
              x = 282,
              y = 1334,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 79,
              name = "",
              type = "enemy",
              shape = "point",
              x = 282,
              y = 1354,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 80,
              name = "",
              type = "enemy",
              shape = "point",
              x = 262,
              y = 1354,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 81,
              name = "",
              type = "enemy",
              shape = "point",
              x = 258,
              y = 1392,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 82,
              name = "",
              type = "enemy",
              shape = "point",
              x = 294,
              y = 1400,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 83,
              name = "",
              type = "enemy",
              shape = "point",
              x = 318,
              y = 1366,
              width = 0,
              height = 0,
              rotation = 0,
              visible = true,
              properties = {}
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 9,
          name = "Object Layer 5",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 84,
              name = "",
              type = "counter",
              shape = "rectangle",
              x = 256,
              y = 640,
              width = 256,
              height = 128,
              rotation = 0,
              visible = true,
              properties = {}
            }
          }
        }
      }
    }
  }
}
